// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -package=ocm -destination=mock_ocmclient.go
//
// Package ocm is a generated GoMock package.
package ocm
