output "cluster_id" {
  value       = rhcs_cluster_osd_gcp.osd.id
  description = "OCM cluster ID"
}

output "cluster_name" {
  value       = rhcs_cluster_osd_gcp.osd.name
  description = "OSD cluster name"
}

output "api_url" {
  value       = rhcs_cluster_osd_gcp.osd.api_url
  description = "Kubernetes API endpoint (private PSC URL)"
}

output "console_url" {
  value       = rhcs_cluster_osd_gcp.osd.console_url
  description = "OpenShift console URL"
}

output "wif_config_id" {
  value       = rhcs_wif_config.wif.id
  description = "OCM WIF config ID consumed by the cluster"
}

output "kms_key_self_link" {
  value       = google_kms_crypto_key.osd.id
  description = "CMEK key resource path"
}

output "admin_username" {
  value       = try(rhcs_cluster_osd_gcp.osd.admin_credentials.username, null)
  description = "Inline cluster-admin username (htpasswd IDP). Null when the cluster was imported (OCM does not return credentials on Read)."
}

output "admin_password" {
  value       = try(rhcs_cluster_osd_gcp.osd.admin_credentials.password, null)
  sensitive   = true
  description = "Inline cluster-admin password (generated by the provider if not supplied). Null when the cluster was imported."
}
