// Code generated by pathbind-gen --mode=tf. DO NOT EDIT.
// Source: pathbind-overrides.yaml

package hyperfleet

import (
	"context"
	"fmt"
	"math"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	hyperfleet "github.com/openshift-online/rosa-hyperfleet-api/clientset"
	pathbind "github.com/openshift-online/rosa-hyperfleet-api/clientset/pathbind"
	hfwrappers "github.com/openshift-online/rosa-hyperfleet-api/clientset/platform"

	"github.com/terraform-redhat/terraform-provider-rhcs/provider/providerdata"
)

var _ resource.Resource = &ClusterResource{}
var _ resource.ResourceWithConfigure = &ClusterResource{}
var _ resource.ResourceWithImportState = &ClusterResource{}

// NewCluster creates a new Cluster resource.
func NewCluster() resource.Resource {
	return &ClusterResource{}
}

// ClusterHandler defines consumer-specific logic for Cluster operations.
type ClusterHandler interface {
	// PreExpand is called before pathbind.Expand to validate inputs and derive computed fields.
	// Example: validate name length, compute RolesRef from prefix, derive region from AZs.
	PreExpand(ctx context.Context, input *ClusterState) diag.Diagnostics

	// PostExpand is called after pathbind.Expand and before the API call.
	// Use this to set SDK fields that pathbind cannot express (enum constants, computed structs).
	PostExpand(ctx context.Context, input *ClusterState, obj *v1alpha1.Cluster) diag.Diagnostics

	// PostResponse is called after API calls (Create, Read, Update, Delete).
	// Use this for output formatting, side effects, and post-processing.
	PostResponse(ctx context.Context, resp *v1alpha1.Cluster) diag.Diagnostics

	// PostFlatten is called after pathbind.Flatten converts API response to state.
	// Use this to populate computed fields, adjust state values, or perform post-processing
	// that requires access to both the API response and the state being built.
	PostFlatten(ctx context.Context, state *ClusterState, resp *v1alpha1.Cluster)
}

// ClusterResource manages Cluster resources via the hyperfleet Platform API.
type ClusterResource struct {
	// Client is the hyperfleet SDK client configured by the provider.
	Client hyperfleet.Interface

	// AccountID is the AWS account ID configured by the provider.
	AccountID string

	// CallerARN is the SigV4 caller ARN configured by the provider.
	CallerARN string

	// Handler is the consumer-provided implementation of ClusterHandler.
	Handler ClusterHandler
}

func (r *ClusterResource) Metadata(
	_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_cluster_hyperfleet"
}

func (r *ClusterResource) Configure(
	_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse,
) {
	if req.ProviderData == nil {
		return
	}

	shared, ok := req.ProviderData.(*providerdata.ProviderSharedData)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *providerdata.ProviderSharedData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.Client = shared.HyperfleetClient
	r.AccountID = shared.HyperfleetAccountID
	r.CallerARN = shared.HyperfleetCallerARN

	// Initialize the handler via factory function
	r.Handler = NewClusterHandlerImpl(shared.HyperfleetClient, shared.HyperfleetAccountID, shared.HyperfleetCallerARN)
}

func (r *ClusterResource) Schema(
	_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse,
) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages Cluster resources.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Id.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"delete_protection": schema.BoolAttribute{
				MarkdownDescription: "Delete_protection.",
				Optional:            true,
			},
			"display_name": schema.StringAttribute{
				MarkdownDescription: "Display_name.",
				Optional:            true,
			},
			"expiration_timestamp": schema.StringAttribute{
				MarkdownDescription: "Expiration_timestamp.",
				Optional:            true,
			},
			"role_arn": schema.StringAttribute{
				MarkdownDescription: "RoleARN.",
				Optional:            true,
			},
			"platform": schema.StringAttribute{
				MarkdownDescription: "Platform.",
				Optional:            true,
			},
			"provisioner_config_name": schema.StringAttribute{
				MarkdownDescription: "ProvisionerConfigName.",
				Optional:            true,
			},
			"container_log_max_files": schema.Int64Attribute{
				MarkdownDescription: "ContainerLogMaxFiles.",
				Optional:            true,
			},
			"container_log_max_size": schema.StringAttribute{
				MarkdownDescription: "ContainerLogMaxSize.",
				Optional:            true,
			},
			"image_gc_high_threshold_percent": schema.Int64Attribute{
				MarkdownDescription: "ImageGCHighThresholdPercent.",
				Optional:            true,
			},
			"image_gc_low_threshold_percent": schema.Int64Attribute{
				MarkdownDescription: "ImageGCLowThresholdPercent.",
				Optional:            true,
			},
			"image_minimum_gc_age": schema.StringAttribute{
				MarkdownDescription: "ImageMinimumGCAge.",
				Optional:            true,
			},
			"kube_reserved": schema.MapAttribute{
				MarkdownDescription: "KubeReserved.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"max_pods": schema.Int64Attribute{
				MarkdownDescription: "MaxPods.",
				Optional:            true,
			},
			"pod_pids_limit": schema.Int64Attribute{
				MarkdownDescription: "PodPidsLimit.",
				Optional:            true,
			},
			"registry_burst": schema.Int64Attribute{
				MarkdownDescription: "RegistryBurst.",
				Optional:            true,
			},
			"registry_pull_qps": schema.Int64Attribute{
				MarkdownDescription: "RegistryPullQPS.",
				Optional:            true,
			},
			"serialize_image_pulls": schema.BoolAttribute{
				MarkdownDescription: "SerializeImagePulls.",
				Optional:            true,
			},
			"streaming_connection_idle_timeout": schema.StringAttribute{
				MarkdownDescription: "StreamingConnectionIdleTimeout.",
				Optional:            true,
			},
			"system_reserved": schema.MapAttribute{
				MarkdownDescription: "SystemReserved.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"allowed_kernel_arguments": schema.StringAttribute{
				MarkdownDescription: "AllowedKernelArguments.",
				Optional:            true,
			},
			"image_content_sources": schema.StringAttribute{
				MarkdownDescription: "ImageContentSources.",
				Optional:            true,
			},
			"allocate_node_cidrs": schema.StringAttribute{
				MarkdownDescription: "AllocateNodeCIDRs.",
				Optional:            true,
			},
			"advertise_address": schema.StringAttribute{
				MarkdownDescription: "AdvertiseAddress.",
				Optional:            true,
			},
			"allowed_cidr_blocks": schema.StringAttribute{
				MarkdownDescription: "AllowedCIDRBlocks.",
				Optional:            true,
			},
			"port": schema.Int64Attribute{
				MarkdownDescription: "Port.",
				Optional:            true,
			},
			"cluster_network": schema.StringAttribute{
				MarkdownDescription: "ClusterNetwork.",
				Optional:            true,
			},
			"machine_network": schema.StringAttribute{
				MarkdownDescription: "MachineNetwork.",
				Optional:            true,
			},
			"network_type": schema.StringAttribute{
				MarkdownDescription: "NetworkType.",
				Optional:            true,
			},
			"service_network": schema.StringAttribute{
				MarkdownDescription: "ServiceNetwork.",
				Optional:            true,
			},
			"additional_allowed_principals": schema.StringAttribute{
				MarkdownDescription: "AdditionalAllowedPrincipals.",
				Optional:            true,
			},
			"filters": schema.StringAttribute{
				MarkdownDescription: "Filters.",
				Optional:            true,
			},
			"subnet_id": schema.StringAttribute{
				MarkdownDescription: "Subnet_id.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"vpc": schema.StringAttribute{
				MarkdownDescription: "Vpc.",
				Optional:            true,
			},
			"zone": schema.StringAttribute{
				MarkdownDescription: "Zone.",
				Optional:            true,
			},
			"endpoint_access": schema.StringAttribute{
				MarkdownDescription: "EndpointAccess.",
				Optional:            true,
			},
			"multi_arch": schema.BoolAttribute{
				MarkdownDescription: "MultiArch.",
				Optional:            true,
			},
			"region": schema.StringAttribute{
				MarkdownDescription: "Region.",
				Optional:            true,
			},
			"resource_tags": schema.StringAttribute{
				MarkdownDescription: "ResourceTags.",
				Optional:            true,
			},
			"control_plane_operator_arn": schema.StringAttribute{
				MarkdownDescription: "ControlPlaneOperatorARN.",
				Optional:            true,
			},
			"image_registry_arn": schema.StringAttribute{
				MarkdownDescription: "ImageRegistryARN.",
				Optional:            true,
			},
			"aws_roles_ref_ingress_arn": schema.StringAttribute{
				MarkdownDescription: "AwsRolesRefIngressARN.",
				Optional:            true,
			},
			"kube_cloud_controller_arn": schema.StringAttribute{
				MarkdownDescription: "KubeCloudControllerARN.",
				Optional:            true,
			},
			"network_arn": schema.StringAttribute{
				MarkdownDescription: "NetworkARN.",
				Optional:            true,
			},
			"node_pool_management_arn": schema.StringAttribute{
				MarkdownDescription: "NodePoolManagementARN.",
				Optional:            true,
			},
			"storage_arn": schema.StringAttribute{
				MarkdownDescription: "StorageARN.",
				Optional:            true,
			},
			"service_endpoints": schema.StringAttribute{
				MarkdownDescription: "ServiceEndpoints.",
				Optional:            true,
			},
			"local_zone_id": schema.StringAttribute{
				MarkdownDescription: "LocalZoneID.",
				Optional:            true,
			},
			"control_plane_arn": schema.StringAttribute{
				MarkdownDescription: "ControlPlaneARN.",
				Optional:            true,
			},
			"shared_vpc_roles_ref_ingress_arn": schema.StringAttribute{
				MarkdownDescription: "SharedVPCRolesRefIngressARN.",
				Optional:            true,
			},
			"termination_handler_queue_url": schema.StringAttribute{
				MarkdownDescription: "TerminationHandlerQueueURL.",
				Optional:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Type.",
				Optional:            true,
			},
			"image": schema.StringAttribute{
				MarkdownDescription: "Image.",
				Optional:            true,
			},
			"oidc_config_id": schema.StringAttribute{
				MarkdownDescription: "OidcConfigId.",
				Optional:            true,
			},
			"properties": schema.MapAttribute{
				MarkdownDescription: "Properties.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"tags": schema.MapAttribute{
				MarkdownDescription: "Tags.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"operator_roles_prefix": schema.StringAttribute{
				MarkdownDescription: "Operator_roles_prefix.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"aws_subnet_ids": schema.ListAttribute{
				MarkdownDescription: "Aws_subnet_ids.",
				Required:            true,
				ElementType:         types.StringType,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
			},
			"vpc_id": schema.StringAttribute{
				MarkdownDescription: "Vpc_id.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"availability_zones": schema.ListAttribute{
				MarkdownDescription: "Availability_zones.",
				Required:            true,
				ElementType:         types.StringType,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
			},
			"aws_partition": schema.StringAttribute{
				MarkdownDescription: "Aws_partition.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cloud_region": schema.StringAttribute{
				MarkdownDescription: "Cloud_region.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown(),
				},
			},
			"api_url": schema.StringAttribute{
				MarkdownDescription: "Api_url.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"phase": schema.StringAttribute{
				MarkdownDescription: "Phase.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *ClusterResource) Create(
	ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage Cluster resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var plan ClusterState
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call handler for validation and derivation
	diags := r.Handler.PreExpand(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert Terraform state to native Go struct for pathbind
	native, conversionDiags := terraformClusterToNative(&plan)
	resp.Diagnostics.Append(conversionDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Fetch the current object so fields not represented in Terraform are preserved.
	obj, err := r.Client.HyperfleetV1alpha1().Clusters().Get(ctx, plan.Id.ValueString(), hfwrappers.GetOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to read Cluster for update", err.Error())
		return
	}

	// Expand the Terraform plan into the current SDK object.
	if err := pathbind.Expand(ctx, native, obj); err != nil {
		resp.Diagnostics.AddError("Failed to expand plan to SDK struct", err.Error())
		return
	}

	// Call handler for setting unmappable fields
	diags = r.Handler.PostExpand(ctx, &plan, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create via API
	// For namespaced resources, obj.GetNamespace() reflects the value the handler's
	// PostExpand set on the SDK object; passing it here keeps the client-scoped
	// namespace and the object's namespace in sync.
	created, err := r.Client.HyperfleetV1alpha1().Clusters().Create(ctx, obj, hfwrappers.CreateOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to create Cluster", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState ClusterStateNative
	if err := pathbind.Flatten(ctx, created, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags = r.Handler.PostResponse(ctx, created)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeClusterToTerraform(&nativeState)

	// Merge API response values into plan to preserve consumer-only fields
	// This keeps user-provided values while adding computed fields from the API
	mergeResponseCluster(&plan, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &plan, created)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ClusterResource) Read(
	ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage Cluster resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var state ClusterState
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get current resource from API
	obj, err := r.Client.HyperfleetV1alpha1().Clusters().Get(ctx, state.Id.ValueString(), hfwrappers.GetOptions{})
	if err != nil {
		if isNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Failed to read Cluster", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState ClusterStateNative
	if err := pathbind.Flatten(ctx, obj, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags := r.Handler.PostResponse(ctx, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeClusterToTerraform(&nativeState)

	// Merge API response values into state to preserve consumer-only fields
	// (fields with no SDK path, e.g. immutable creation-only inputs) that
	// would otherwise be lost since they cannot be reconstructed from the API response.
	mergeResponseCluster(&state, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &state, obj)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ClusterResource) Update(
	ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage Cluster resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var plan ClusterState
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call handler for validation and derivation
	diags := r.Handler.PreExpand(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert Terraform state to native Go struct for pathbind
	native, conversionDiags := terraformClusterToNative(&plan)
	resp.Diagnostics.Append(conversionDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create empty SDK struct and expand plan into it
	obj := &v1alpha1.Cluster{}
	if err := pathbind.Expand(ctx, native, obj); err != nil {
		resp.Diagnostics.AddError("Failed to expand plan to SDK struct", err.Error())
		return
	}

	// Call handler for setting unmappable fields
	diags = r.Handler.PostExpand(ctx, &plan, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Update via API
	updated, err := r.Client.HyperfleetV1alpha1().Clusters().Update(ctx, obj, hfwrappers.UpdateOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to update Cluster", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState ClusterStateNative
	if err := pathbind.Flatten(ctx, updated, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags = r.Handler.PostResponse(ctx, updated)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeClusterToTerraform(&nativeState)

	// Merge API response values into plan to preserve consumer-only fields
	// This keeps user-provided values while adding computed fields from the API
	mergeResponseCluster(&plan, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &plan, updated)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ClusterResource) Delete(
	ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage Cluster resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var state ClusterState
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.Client.HyperfleetV1alpha1().Clusters().Delete(ctx, state.Id.ValueString(), hfwrappers.DeleteOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to delete Cluster", err.Error())
		return
	}

	// Call handler for post-delete side effects
	var emptyResp *v1alpha1.Cluster
	diags := r.Handler.PostResponse(ctx, emptyResp)
	resp.Diagnostics.Append(diags...)
}

func (r *ClusterResource) ImportState(
	ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage Cluster resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	// Use the ID passed in as the Cluster identifier
	obj, err := r.Client.HyperfleetV1alpha1().Clusters().Get(ctx, req.ID, hfwrappers.GetOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to import Cluster", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState ClusterStateNative
	if err := pathbind.Flatten(ctx, obj, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags := r.Handler.PostResponse(ctx, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	state := nativeClusterToTerraform(&nativeState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, state, obj)

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Helper functions for state conversion

// terraformClusterToNative converts Terraform framework types to native Go types.
// This is used before pathbind.Expand to prepare input for API calls.
func terraformClusterToNative(tf *ClusterState) (*ClusterStateNative, diag.Diagnostics) {
	if tf == nil {
		return nil, nil
	}
	native := &ClusterStateNative{}
	var diags diag.Diagnostics
	if !tf.Name.IsNull() && !tf.Name.IsUnknown() {
		native.Name = tf.Name.ValueString()
	}
	if !tf.Id.IsNull() && !tf.Id.IsUnknown() {
		native.Id = tf.Id.ValueString()
	}
	if !tf.Delete_protection.IsNull() && !tf.Delete_protection.IsUnknown() {
		native.Delete_protection = tf.Delete_protection.ValueBool()
	}
	if !tf.Display_name.IsNull() && !tf.Display_name.IsUnknown() {
		native.Display_name = tf.Display_name.ValueString()
	}
	if !tf.Expiration_timestamp.IsNull() && !tf.Expiration_timestamp.IsUnknown() {
		native.Expiration_timestamp = tf.Expiration_timestamp.ValueString()
	}
	if !tf.RoleARN.IsNull() && !tf.RoleARN.IsUnknown() {
		native.RoleARN = tf.RoleARN.ValueString()
	}
	if !tf.Platform.IsNull() && !tf.Platform.IsUnknown() {
		native.Platform = tf.Platform.ValueString()
	}
	if !tf.ProvisionerConfigName.IsNull() && !tf.ProvisionerConfigName.IsUnknown() {
		native.ProvisionerConfigName = tf.ProvisionerConfigName.ValueString()
	}
	if !tf.ContainerLogMaxFiles.IsNull() && !tf.ContainerLogMaxFiles.IsUnknown() {
		value := tf.ContainerLogMaxFiles.ValueInt64()
		if value < math.MinInt32 || value > math.MaxInt32 {
			diags.AddError("Invalid int32 value", fmt.Sprintf("field ContainerLogMaxFiles value %d is outside the int32 range", value))
		} else {
			i := int32(value)
			native.ContainerLogMaxFiles = &i
		}
	}
	if !tf.ContainerLogMaxSize.IsNull() && !tf.ContainerLogMaxSize.IsUnknown() {
		native.ContainerLogMaxSize = tf.ContainerLogMaxSize.ValueString()
	}
	if !tf.ImageGCHighThresholdPercent.IsNull() && !tf.ImageGCHighThresholdPercent.IsUnknown() {
		value := tf.ImageGCHighThresholdPercent.ValueInt64()
		if value < math.MinInt32 || value > math.MaxInt32 {
			diags.AddError("Invalid int32 value", fmt.Sprintf("field ImageGCHighThresholdPercent value %d is outside the int32 range", value))
		} else {
			i := int32(value)
			native.ImageGCHighThresholdPercent = &i
		}
	}
	if !tf.ImageGCLowThresholdPercent.IsNull() && !tf.ImageGCLowThresholdPercent.IsUnknown() {
		value := tf.ImageGCLowThresholdPercent.ValueInt64()
		if value < math.MinInt32 || value > math.MaxInt32 {
			diags.AddError("Invalid int32 value", fmt.Sprintf("field ImageGCLowThresholdPercent value %d is outside the int32 range", value))
		} else {
			i := int32(value)
			native.ImageGCLowThresholdPercent = &i
		}
	}
	if !tf.ImageMinimumGCAge.IsNull() && !tf.ImageMinimumGCAge.IsUnknown() {
		native.ImageMinimumGCAge = tf.ImageMinimumGCAge.ValueString()
	}
	if !tf.KubeReserved.IsNull() && !tf.KubeReserved.IsUnknown() {
		values, collectionDiags := terraformMapToStringMap(tf.KubeReserved)
		diags = append(diags, collectionDiags...)
		native.KubeReserved = values
	}
	if !tf.MaxPods.IsNull() && !tf.MaxPods.IsUnknown() {
		value := tf.MaxPods.ValueInt64()
		if value < math.MinInt32 || value > math.MaxInt32 {
			diags.AddError("Invalid int32 value", fmt.Sprintf("field MaxPods value %d is outside the int32 range", value))
		} else {
			i := int32(value)
			native.MaxPods = &i
		}
	}
	if !tf.PodPidsLimit.IsNull() && !tf.PodPidsLimit.IsUnknown() {
		i := tf.PodPidsLimit.ValueInt64()
		native.PodPidsLimit = &i
	}
	if !tf.RegistryBurst.IsNull() && !tf.RegistryBurst.IsUnknown() {
		value := tf.RegistryBurst.ValueInt64()
		if value < math.MinInt32 || value > math.MaxInt32 {
			diags.AddError("Invalid int32 value", fmt.Sprintf("field RegistryBurst value %d is outside the int32 range", value))
		} else {
			i := int32(value)
			native.RegistryBurst = &i
		}
	}
	if !tf.RegistryPullQPS.IsNull() && !tf.RegistryPullQPS.IsUnknown() {
		value := tf.RegistryPullQPS.ValueInt64()
		if value < math.MinInt32 || value > math.MaxInt32 {
			diags.AddError("Invalid int32 value", fmt.Sprintf("field RegistryPullQPS value %d is outside the int32 range", value))
		} else {
			i := int32(value)
			native.RegistryPullQPS = &i
		}
	}
	if !tf.SerializeImagePulls.IsNull() && !tf.SerializeImagePulls.IsUnknown() {
		b := tf.SerializeImagePulls.ValueBool()
		native.SerializeImagePulls = &b
	}
	if !tf.StreamingConnectionIdleTimeout.IsNull() && !tf.StreamingConnectionIdleTimeout.IsUnknown() {
		native.StreamingConnectionIdleTimeout = tf.StreamingConnectionIdleTimeout.ValueString()
	}
	if !tf.SystemReserved.IsNull() && !tf.SystemReserved.IsUnknown() {
		values, collectionDiags := terraformMapToStringMap(tf.SystemReserved)
		diags = append(diags, collectionDiags...)
		native.SystemReserved = values
	}
	if !tf.AllowedKernelArguments.IsNull() && !tf.AllowedKernelArguments.IsUnknown() {
		native.AllowedKernelArguments = tf.AllowedKernelArguments.ValueString()
	}
	if !tf.ImageContentSources.IsNull() && !tf.ImageContentSources.IsUnknown() {
		native.ImageContentSources = tf.ImageContentSources.ValueString()
	}
	if !tf.AllocateNodeCIDRs.IsNull() && !tf.AllocateNodeCIDRs.IsUnknown() {
		native.AllocateNodeCIDRs = tf.AllocateNodeCIDRs.ValueString()
	}
	if !tf.AdvertiseAddress.IsNull() && !tf.AdvertiseAddress.IsUnknown() {
		native.AdvertiseAddress = tf.AdvertiseAddress.ValueString()
	}
	if !tf.AllowedCIDRBlocks.IsNull() && !tf.AllowedCIDRBlocks.IsUnknown() {
		native.AllowedCIDRBlocks = tf.AllowedCIDRBlocks.ValueString()
	}
	if !tf.Port.IsNull() && !tf.Port.IsUnknown() {
		value := tf.Port.ValueInt64()
		if value < math.MinInt32 || value > math.MaxInt32 {
			diags.AddError("Invalid int32 value", fmt.Sprintf("field Port value %d is outside the int32 range", value))
		} else {
			i := int32(value)
			native.Port = &i
		}
	}
	if !tf.ClusterNetwork.IsNull() && !tf.ClusterNetwork.IsUnknown() {
		native.ClusterNetwork = tf.ClusterNetwork.ValueString()
	}
	if !tf.MachineNetwork.IsNull() && !tf.MachineNetwork.IsUnknown() {
		native.MachineNetwork = tf.MachineNetwork.ValueString()
	}
	if !tf.NetworkType.IsNull() && !tf.NetworkType.IsUnknown() {
		native.NetworkType = tf.NetworkType.ValueString()
	}
	if !tf.ServiceNetwork.IsNull() && !tf.ServiceNetwork.IsUnknown() {
		native.ServiceNetwork = tf.ServiceNetwork.ValueString()
	}
	if !tf.AdditionalAllowedPrincipals.IsNull() && !tf.AdditionalAllowedPrincipals.IsUnknown() {
		native.AdditionalAllowedPrincipals = tf.AdditionalAllowedPrincipals.ValueString()
	}
	if !tf.Filters.IsNull() && !tf.Filters.IsUnknown() {
		native.Filters = tf.Filters.ValueString()
	}
	if !tf.Subnet_id.IsNull() && !tf.Subnet_id.IsUnknown() {
		native.Subnet_id = tf.Subnet_id.ValueString()
	}
	if !tf.Vpc.IsNull() && !tf.Vpc.IsUnknown() {
		native.Vpc = tf.Vpc.ValueString()
	}
	if !tf.Zone.IsNull() && !tf.Zone.IsUnknown() {
		native.Zone = tf.Zone.ValueString()
	}
	if !tf.EndpointAccess.IsNull() && !tf.EndpointAccess.IsUnknown() {
		native.EndpointAccess = tf.EndpointAccess.ValueString()
	}
	if !tf.MultiArch.IsNull() && !tf.MultiArch.IsUnknown() {
		b := tf.MultiArch.ValueBool()
		native.MultiArch = &b
	}
	if !tf.Region.IsNull() && !tf.Region.IsUnknown() {
		native.Region = tf.Region.ValueString()
	}
	if !tf.ResourceTags.IsNull() && !tf.ResourceTags.IsUnknown() {
		native.ResourceTags = tf.ResourceTags.ValueString()
	}
	if !tf.ControlPlaneOperatorARN.IsNull() && !tf.ControlPlaneOperatorARN.IsUnknown() {
		native.ControlPlaneOperatorARN = tf.ControlPlaneOperatorARN.ValueString()
	}
	if !tf.ImageRegistryARN.IsNull() && !tf.ImageRegistryARN.IsUnknown() {
		native.ImageRegistryARN = tf.ImageRegistryARN.ValueString()
	}
	if !tf.AwsRolesRefIngressARN.IsNull() && !tf.AwsRolesRefIngressARN.IsUnknown() {
		native.AwsRolesRefIngressARN = tf.AwsRolesRefIngressARN.ValueString()
	}
	if !tf.KubeCloudControllerARN.IsNull() && !tf.KubeCloudControllerARN.IsUnknown() {
		native.KubeCloudControllerARN = tf.KubeCloudControllerARN.ValueString()
	}
	if !tf.NetworkARN.IsNull() && !tf.NetworkARN.IsUnknown() {
		native.NetworkARN = tf.NetworkARN.ValueString()
	}
	if !tf.NodePoolManagementARN.IsNull() && !tf.NodePoolManagementARN.IsUnknown() {
		native.NodePoolManagementARN = tf.NodePoolManagementARN.ValueString()
	}
	if !tf.StorageARN.IsNull() && !tf.StorageARN.IsUnknown() {
		native.StorageARN = tf.StorageARN.ValueString()
	}
	if !tf.ServiceEndpoints.IsNull() && !tf.ServiceEndpoints.IsUnknown() {
		native.ServiceEndpoints = tf.ServiceEndpoints.ValueString()
	}
	if !tf.LocalZoneID.IsNull() && !tf.LocalZoneID.IsUnknown() {
		native.LocalZoneID = tf.LocalZoneID.ValueString()
	}
	if !tf.ControlPlaneARN.IsNull() && !tf.ControlPlaneARN.IsUnknown() {
		native.ControlPlaneARN = tf.ControlPlaneARN.ValueString()
	}
	if !tf.SharedVPCRolesRefIngressARN.IsNull() && !tf.SharedVPCRolesRefIngressARN.IsUnknown() {
		native.SharedVPCRolesRefIngressARN = tf.SharedVPCRolesRefIngressARN.ValueString()
	}
	if !tf.TerminationHandlerQueueURL.IsNull() && !tf.TerminationHandlerQueueURL.IsUnknown() {
		native.TerminationHandlerQueueURL = tf.TerminationHandlerQueueURL.ValueString()
	}
	if !tf.Type.IsNull() && !tf.Type.IsUnknown() {
		native.Type = tf.Type.ValueString()
	}
	if !tf.Image.IsNull() && !tf.Image.IsUnknown() {
		native.Image = tf.Image.ValueString()
	}
	if !tf.OidcConfigId.IsNull() && !tf.OidcConfigId.IsUnknown() {
		native.OidcConfigId = tf.OidcConfigId.ValueString()
	}
	if !tf.Properties.IsNull() && !tf.Properties.IsUnknown() {
		values, collectionDiags := terraformMapToStringMap(tf.Properties)
		diags = append(diags, collectionDiags...)
		native.Properties = values
	}
	if !tf.Tags.IsNull() && !tf.Tags.IsUnknown() {
		values, collectionDiags := terraformMapToStringMap(tf.Tags)
		diags = append(diags, collectionDiags...)
		native.Tags = values
	}
	if !tf.Operator_roles_prefix.IsNull() && !tf.Operator_roles_prefix.IsUnknown() {
		native.Operator_roles_prefix = tf.Operator_roles_prefix.ValueString()
	}
	if !tf.Aws_subnet_ids.IsNull() && !tf.Aws_subnet_ids.IsUnknown() {
		items, collectionDiags := terraformListToStringSlice(tf.Aws_subnet_ids)
		diags = append(diags, collectionDiags...)
		native.Aws_subnet_ids = items
	}
	if !tf.Vpc_id.IsNull() && !tf.Vpc_id.IsUnknown() {
		native.Vpc_id = tf.Vpc_id.ValueString()
	}
	if !tf.Availability_zones.IsNull() && !tf.Availability_zones.IsUnknown() {
		items, collectionDiags := terraformListToStringSlice(tf.Availability_zones)
		diags = append(diags, collectionDiags...)
		native.Availability_zones = items
	}
	if !tf.Aws_partition.IsNull() && !tf.Aws_partition.IsUnknown() {
		native.Aws_partition = tf.Aws_partition.ValueString()
	}
	if !tf.Cloud_region.IsNull() && !tf.Cloud_region.IsUnknown() {
		native.Cloud_region = tf.Cloud_region.ValueString()
	}
	if !tf.Api_url.IsNull() && !tf.Api_url.IsUnknown() {
		native.Api_url = tf.Api_url.ValueString()
	}
	if !tf.Phase.IsNull() && !tf.Phase.IsUnknown() {
		native.Phase = tf.Phase.ValueString()
	}
	return native, diags
}

// nativeClusterToTerraform converts native Go types to Terraform framework types.
// This is used after pathbind.Flatten to prepare output for state persistence.
func nativeClusterToTerraform(native *ClusterStateNative) *ClusterState {
	if native == nil {
		return nil
	}
	tf := &ClusterState{}
	tf.Name = toTerraformString(native.Name)
	tf.Id = toTerraformString(native.Id)
	tf.Delete_protection = toTerraformBool(native.Delete_protection)
	tf.Display_name = toTerraformString(native.Display_name)
	tf.Expiration_timestamp = toTerraformString(native.Expiration_timestamp)
	tf.RoleARN = toTerraformString(native.RoleARN)
	tf.Platform = toTerraformString(native.Platform)
	tf.ProvisionerConfigName = toTerraformString(native.ProvisionerConfigName)
	tf.ContainerLogMaxFiles = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.ContainerLogMaxFiles))
	tf.ContainerLogMaxSize = toTerraformString(native.ContainerLogMaxSize)
	tf.ImageGCHighThresholdPercent = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.ImageGCHighThresholdPercent))
	tf.ImageGCLowThresholdPercent = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.ImageGCLowThresholdPercent))
	tf.ImageMinimumGCAge = toTerraformString(native.ImageMinimumGCAge)
	tf.KubeReserved = toTerraformMap(native.KubeReserved)
	tf.MaxPods = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.MaxPods))
	tf.PodPidsLimit = toTerraformInt64Ptr(normalizeOptionalInt64(native.PodPidsLimit))
	tf.RegistryBurst = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.RegistryBurst))
	tf.RegistryPullQPS = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.RegistryPullQPS))
	tf.SerializeImagePulls = toTerraformBoolPtr(native.SerializeImagePulls)
	tf.StreamingConnectionIdleTimeout = toTerraformString(native.StreamingConnectionIdleTimeout)
	tf.SystemReserved = toTerraformMap(native.SystemReserved)
	tf.AllowedKernelArguments = toTerraformString(native.AllowedKernelArguments)
	tf.ImageContentSources = toTerraformString(native.ImageContentSources)
	tf.AllocateNodeCIDRs = toTerraformString(native.AllocateNodeCIDRs)
	tf.AdvertiseAddress = toTerraformString(native.AdvertiseAddress)
	tf.AllowedCIDRBlocks = toTerraformString(native.AllowedCIDRBlocks)
	tf.Port = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.Port))
	tf.ClusterNetwork = toTerraformString(native.ClusterNetwork)
	tf.MachineNetwork = toTerraformString(native.MachineNetwork)
	tf.NetworkType = toTerraformString(native.NetworkType)
	tf.ServiceNetwork = toTerraformString(native.ServiceNetwork)
	tf.AdditionalAllowedPrincipals = toTerraformString(native.AdditionalAllowedPrincipals)
	tf.Filters = toTerraformString(native.Filters)
	tf.Subnet_id = toTerraformString(native.Subnet_id)
	tf.Vpc = toTerraformString(native.Vpc)
	tf.Zone = toTerraformString(native.Zone)
	tf.EndpointAccess = toTerraformString(native.EndpointAccess)
	tf.MultiArch = toTerraformBoolPtr(native.MultiArch)
	tf.Region = toTerraformString(native.Region)
	tf.ResourceTags = toTerraformString(native.ResourceTags)
	tf.ControlPlaneOperatorARN = toTerraformString(native.ControlPlaneOperatorARN)
	tf.ImageRegistryARN = toTerraformString(native.ImageRegistryARN)
	tf.AwsRolesRefIngressARN = toTerraformString(native.AwsRolesRefIngressARN)
	tf.KubeCloudControllerARN = toTerraformString(native.KubeCloudControllerARN)
	tf.NetworkARN = toTerraformString(native.NetworkARN)
	tf.NodePoolManagementARN = toTerraformString(native.NodePoolManagementARN)
	tf.StorageARN = toTerraformString(native.StorageARN)
	tf.ServiceEndpoints = toTerraformString(native.ServiceEndpoints)
	tf.LocalZoneID = toTerraformString(native.LocalZoneID)
	tf.ControlPlaneARN = toTerraformString(native.ControlPlaneARN)
	tf.SharedVPCRolesRefIngressARN = toTerraformString(native.SharedVPCRolesRefIngressARN)
	tf.TerminationHandlerQueueURL = toTerraformString(native.TerminationHandlerQueueURL)
	tf.Type = toTerraformString(native.Type)
	tf.Image = toTerraformString(native.Image)
	tf.OidcConfigId = toTerraformString(native.OidcConfigId)
	tf.Properties = toTerraformMap(native.Properties)
	tf.Tags = toTerraformMap(native.Tags)
	tf.Operator_roles_prefix = toTerraformString(native.Operator_roles_prefix)
	tf.Aws_subnet_ids = toTerraformList(native.Aws_subnet_ids)
	tf.Vpc_id = toTerraformString(native.Vpc_id)
	tf.Availability_zones = toTerraformList(native.Availability_zones)
	tf.Aws_partition = toTerraformString(native.Aws_partition)
	tf.Cloud_region = toTerraformString(native.Cloud_region)
	tf.Api_url = toTerraformString(native.Api_url)
	tf.Phase = toTerraformString(native.Phase)
	return tf
}
