// Code generated by pathbind-gen --mode=tf. DO NOT EDIT.
// Source: pathbind-overrides.yaml

package hyperfleet

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ClusterState holds Terraform state and plan data for Cluster resources.
// This struct is used for Terraform schema binding (input plan and output state).
// Fields are tagged with tfsdk (Terraform state key) only.
// DO NOT use hfsdk tags here; use ClusterStateNative for pathbind operations.
type ClusterState struct {
	Name                           types.String `tfsdk:"name"`
	Id                             types.String `tfsdk:"id"`
	Delete_protection              types.Bool   `tfsdk:"delete_protection"`
	Display_name                   types.String `tfsdk:"display_name"`
	Expiration_timestamp           types.String `tfsdk:"expiration_timestamp"`
	RoleARN                        types.String `tfsdk:"role_arn"`
	Platform                       types.String `tfsdk:"platform"`
	ProvisionerConfigName          types.String `tfsdk:"provisioner_config_name"`
	ContainerLogMaxFiles           types.Int64  `tfsdk:"container_log_max_files"`
	ContainerLogMaxSize            types.String `tfsdk:"container_log_max_size"`
	ImageGCHighThresholdPercent    types.Int64  `tfsdk:"image_gc_high_threshold_percent"`
	ImageGCLowThresholdPercent     types.Int64  `tfsdk:"image_gc_low_threshold_percent"`
	ImageMinimumGCAge              types.String `tfsdk:"image_minimum_gc_age"`
	KubeReserved                   types.Map    `tfsdk:"kube_reserved"`
	MaxPods                        types.Int64  `tfsdk:"max_pods"`
	PodPidsLimit                   types.Int64  `tfsdk:"pod_pids_limit"`
	RegistryBurst                  types.Int64  `tfsdk:"registry_burst"`
	RegistryPullQPS                types.Int64  `tfsdk:"registry_pull_qps"`
	SerializeImagePulls            types.Bool   `tfsdk:"serialize_image_pulls"`
	StreamingConnectionIdleTimeout types.String `tfsdk:"streaming_connection_idle_timeout"`
	SystemReserved                 types.Map    `tfsdk:"system_reserved"`
	AllowedKernelArguments         types.String `tfsdk:"allowed_kernel_arguments"`
	ImageContentSources            types.String `tfsdk:"image_content_sources"`
	AllocateNodeCIDRs              types.String `tfsdk:"allocate_node_cidrs"`
	AdvertiseAddress               types.String `tfsdk:"advertise_address"`
	AllowedCIDRBlocks              types.String `tfsdk:"allowed_cidr_blocks"`
	Port                           types.Int64  `tfsdk:"port"`
	ClusterNetwork                 types.String `tfsdk:"cluster_network"`
	MachineNetwork                 types.String `tfsdk:"machine_network"`
	NetworkType                    types.String `tfsdk:"network_type"`
	ServiceNetwork                 types.String `tfsdk:"service_network"`
	AdditionalAllowedPrincipals    types.String `tfsdk:"additional_allowed_principals"`
	Filters                        types.String `tfsdk:"filters"`
	Subnet_id                      types.String `tfsdk:"subnet_id"`
	Vpc                            types.String `tfsdk:"vpc"`
	Zone                           types.String `tfsdk:"zone"`
	EndpointAccess                 types.String `tfsdk:"endpoint_access"`
	MultiArch                      types.Bool   `tfsdk:"multi_arch"`
	Region                         types.String `tfsdk:"region"`
	ResourceTags                   types.String `tfsdk:"resource_tags"`
	ControlPlaneOperatorARN        types.String `tfsdk:"control_plane_operator_arn"`
	ImageRegistryARN               types.String `tfsdk:"image_registry_arn"`
	AwsRolesRefIngressARN          types.String `tfsdk:"aws_roles_ref_ingress_arn"`
	KubeCloudControllerARN         types.String `tfsdk:"kube_cloud_controller_arn"`
	NetworkARN                     types.String `tfsdk:"network_arn"`
	NodePoolManagementARN          types.String `tfsdk:"node_pool_management_arn"`
	StorageARN                     types.String `tfsdk:"storage_arn"`
	ServiceEndpoints               types.String `tfsdk:"service_endpoints"`
	LocalZoneID                    types.String `tfsdk:"local_zone_id"`
	ControlPlaneARN                types.String `tfsdk:"control_plane_arn"`
	SharedVPCRolesRefIngressARN    types.String `tfsdk:"shared_vpc_roles_ref_ingress_arn"`
	TerminationHandlerQueueURL     types.String `tfsdk:"termination_handler_queue_url"`
	Type                           types.String `tfsdk:"type"`
	Image                          types.String `tfsdk:"image"`
	OidcConfigId                   types.String `tfsdk:"oidc_config_id"`
	Properties                     types.Map    `tfsdk:"properties"`
	Tags                           types.Map    `tfsdk:"tags"`
	Operator_roles_prefix          types.String `tfsdk:"operator_roles_prefix"`
	Aws_subnet_ids                 types.List   `tfsdk:"aws_subnet_ids"`
	Vpc_id                         types.String `tfsdk:"vpc_id"`
	Availability_zones             types.List   `tfsdk:"availability_zones"`
	Aws_partition                  types.String `tfsdk:"aws_partition"`
	Cloud_region                   types.String `tfsdk:"cloud_region"`
	Api_url                        types.String `tfsdk:"api_url"`
	Phase                          types.String `tfsdk:"phase"`
}

// mergeResponseCluster merges API response values into the plan state.
// Only computed or required fields are merged from the response. Optional fields
// are skipped to preserve user-provided values and avoid overwriting with API defaults.
func mergeResponseCluster(plan, response *ClusterState) {
	if response == nil {
		return
	}
	// Only copy computed and required fields from response, skip optional fields
	// to avoid overwriting user inputs with API-generated default values
	if !response.Name.IsNull() {
		plan.Name = response.Name
	}
	if !response.Id.IsNull() {
		plan.Id = response.Id
	}
	if !response.Subnet_id.IsNull() {
		plan.Subnet_id = response.Subnet_id
	}
	if !response.Operator_roles_prefix.IsNull() {
		plan.Operator_roles_prefix = response.Operator_roles_prefix
	}
	if !response.Aws_subnet_ids.IsNull() {
		plan.Aws_subnet_ids = response.Aws_subnet_ids
	}
	if !response.Vpc_id.IsNull() {
		plan.Vpc_id = response.Vpc_id
	}
	if !response.Availability_zones.IsNull() {
		plan.Availability_zones = response.Availability_zones
	}
	if !response.Aws_partition.IsNull() {
		plan.Aws_partition = response.Aws_partition
	}
	if !response.Cloud_region.IsNull() {
		plan.Cloud_region = response.Cloud_region
	}
	if !response.Api_url.IsNull() {
		plan.Api_url = response.Api_url
	}
	if !response.Phase.IsNull() {
		plan.Phase = response.Phase
	}
}
