// Code generated by pathbind-gen --mode=tf. DO NOT EDIT.
// Source: pathbind-overrides.yaml

package hyperfleet

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// NodePoolState holds Terraform state and plan data for NodePool resources.
// This struct is used for Terraform schema binding (input plan and output state).
// Fields are tagged with tfsdk (Terraform state key) only.
// DO NOT use hfsdk tags here; use NodePoolStateNative for pathbind operations.
type NodePoolState struct {
	Name                          types.String `tfsdk:"name"`
	Id                            types.String `tfsdk:"id"`
	AutoRepair                    types.Bool   `tfsdk:"auto_repair"`
	DisplayName                   types.String `tfsdk:"display_name"`
	Labels                        types.Map    `tfsdk:"labels"`
	ClusterName                   types.String `tfsdk:"cluster_name"`
	Ami                           types.String `tfsdk:"ami"`
	ImageType                     types.String `tfsdk:"image_type"`
	InstanceProfile               types.String `tfsdk:"instance_profile"`
	InstanceType                  types.String `tfsdk:"instance_type"`
	CapacityReservationId         types.String `tfsdk:"capacity_reservation_id"`
	CapacityReservationMarketType types.String `tfsdk:"capacity_reservation_market_type"`
	Preference                    types.String `tfsdk:"preference"`
	PlacementMarketType           types.String `tfsdk:"placement_market_type"`
	MaxPrice                      types.String `tfsdk:"max_price"`
	Tenancy                       types.String `tfsdk:"tenancy"`
	ResourceTags                  types.String `tfsdk:"resource_tags"`
	Encrypted                     types.Bool   `tfsdk:"encrypted"`
	EncryptionKey                 types.String `tfsdk:"encryption_key"`
	Iops                          types.Int64  `tfsdk:"iops"`
	Size                          types.Int64  `tfsdk:"size"`
	RootVolumeType                types.String `tfsdk:"root_volume_type"`
	SecurityGroups                types.String `tfsdk:"security_groups"`
	Filters                       types.String `tfsdk:"filters"`
	SubnetId                      types.String `tfsdk:"subnet_id"`
	Platform_type                 types.String `tfsdk:"platform_type"`
	Image                         types.String `tfsdk:"image"`
	Replicas                      types.Int64  `tfsdk:"replicas"`
	Cluster_id                    types.String `tfsdk:"cluster_id"`
	Phase                         types.String `tfsdk:"phase"`
}

// mergeResponseNodePool merges API response values into the plan state.
// Only computed or required fields are merged from the response. Optional fields
// are skipped to preserve user-provided values and avoid overwriting with API defaults.
func mergeResponseNodePool(plan, response *NodePoolState) {
	if response == nil {
		return
	}
	// Only copy computed and required fields from response, skip optional fields
	// to avoid overwriting user inputs with API-generated default values
	if !response.Id.IsNull() {
		plan.Id = response.Id
	}
	if !response.Platform_type.IsNull() {
		plan.Platform_type = response.Platform_type
	}
	if !response.Cluster_id.IsNull() {
		plan.Cluster_id = response.Cluster_id
	}
	if !response.Phase.IsNull() {
		plan.Phase = response.Phase
	}
}
