// Code generated by pathbind-gen --mode=tf. DO NOT EDIT.
// Source: pathbind-overrides.yaml

package hyperfleet

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	hyperfleet "github.com/openshift-online/rosa-hyperfleet-api/clientset"
	pathbind "github.com/openshift-online/rosa-hyperfleet-api/clientset/pathbind"
	hfwrappers "github.com/openshift-online/rosa-hyperfleet-api/clientset/platform"

	"github.com/terraform-redhat/terraform-provider-rhcs/provider/providerdata"
)

var _ resource.Resource = &NodePoolResource{}
var _ resource.ResourceWithConfigure = &NodePoolResource{}
var _ resource.ResourceWithImportState = &NodePoolResource{}

// NewNodePool creates a new NodePool resource.
func NewNodePool() resource.Resource {
	return &NodePoolResource{}
}

// NodePoolHandler defines consumer-specific logic for NodePool operations.
type NodePoolHandler interface {
	// PreExpand is called before pathbind.Expand to validate inputs and derive computed fields.
	// Example: validate name length, compute RolesRef from prefix, derive region from AZs.
	PreExpand(ctx context.Context, input *NodePoolState) diag.Diagnostics

	// PostExpand is called after pathbind.Expand and before the API call.
	// Use this to set SDK fields that pathbind cannot express (enum constants, computed structs).
	PostExpand(ctx context.Context, input *NodePoolState, obj *v1alpha1.NodePool) diag.Diagnostics

	// PostResponse is called after API calls (Create, Read, Update, Delete).
	// Use this for output formatting, side effects, and post-processing.
	PostResponse(ctx context.Context, resp *v1alpha1.NodePool) diag.Diagnostics

	// PostFlatten is called after pathbind.Flatten converts API response to state.
	// Use this to populate computed fields, adjust state values, or perform post-processing
	// that requires access to both the API response and the state being built.
	PostFlatten(ctx context.Context, state *NodePoolState, resp *v1alpha1.NodePool)
}

// NodePoolResource manages NodePool resources via the hyperfleet Platform API.
type NodePoolResource struct {
	// Client is the hyperfleet SDK client configured by the provider.
	Client hyperfleet.Interface

	// AccountID is the AWS account ID configured by the provider.
	AccountID string

	// CallerARN is the SigV4 caller ARN configured by the provider.
	CallerARN string

	// Handler is the consumer-provided implementation of NodePoolHandler.
	Handler NodePoolHandler
}

func (r *NodePoolResource) Metadata(
	_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_nodepool_hyperfleet"
}

func (r *NodePoolResource) Configure(
	_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse,
) {
	if req.ProviderData == nil {
		return
	}

	shared, ok := req.ProviderData.(*providerdata.ProviderSharedData)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *providerdata.ProviderSharedData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.Client = shared.HyperfleetClient
	r.AccountID = shared.HyperfleetAccountID
	r.CallerARN = shared.HyperfleetCallerARN

	// Initialize the handler via factory function
	r.Handler = NewNodePoolHandlerImpl(shared.HyperfleetClient, shared.HyperfleetAccountID, shared.HyperfleetCallerARN)
}

func (r *NodePoolResource) Schema(
	_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse,
) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages NodePool resources.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Id.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"auto_repair": schema.BoolAttribute{
				MarkdownDescription: "AutoRepair.",
				Optional:            true,
			},
			"display_name": schema.StringAttribute{
				MarkdownDescription: "DisplayName.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"cluster_name": schema.StringAttribute{
				MarkdownDescription: "ClusterName.",
				Optional:            true,
			},
			"ami": schema.StringAttribute{
				MarkdownDescription: "Ami.",
				Optional:            true,
			},
			"image_type": schema.StringAttribute{
				MarkdownDescription: "ImageType.",
				Optional:            true,
			},
			"instance_profile": schema.StringAttribute{
				MarkdownDescription: "InstanceProfile.",
				Optional:            true,
			},
			"instance_type": schema.StringAttribute{
				MarkdownDescription: "InstanceType.",
				Optional:            true,
			},
			"capacity_reservation_id": schema.StringAttribute{
				MarkdownDescription: "CapacityReservationId.",
				Optional:            true,
			},
			"capacity_reservation_market_type": schema.StringAttribute{
				MarkdownDescription: "CapacityReservationMarketType.",
				Optional:            true,
			},
			"preference": schema.StringAttribute{
				MarkdownDescription: "Preference.",
				Optional:            true,
			},
			"placement_market_type": schema.StringAttribute{
				MarkdownDescription: "PlacementMarketType.",
				Optional:            true,
			},
			"max_price": schema.StringAttribute{
				MarkdownDescription: "MaxPrice.",
				Optional:            true,
			},
			"tenancy": schema.StringAttribute{
				MarkdownDescription: "Tenancy.",
				Optional:            true,
			},
			"resource_tags": schema.StringAttribute{
				MarkdownDescription: "ResourceTags.",
				Optional:            true,
			},
			"encrypted": schema.BoolAttribute{
				MarkdownDescription: "Encrypted.",
				Optional:            true,
			},
			"encryption_key": schema.StringAttribute{
				MarkdownDescription: "EncryptionKey.",
				Optional:            true,
			},
			"iops": schema.Int64Attribute{
				MarkdownDescription: "Iops.",
				Optional:            true,
			},
			"size": schema.Int64Attribute{
				MarkdownDescription: "Size.",
				Optional:            true,
			},
			"root_volume_type": schema.StringAttribute{
				MarkdownDescription: "RootVolumeType.",
				Optional:            true,
			},
			"security_groups": schema.StringAttribute{
				MarkdownDescription: "SecurityGroups.",
				Optional:            true,
			},
			"filters": schema.StringAttribute{
				MarkdownDescription: "Filters.",
				Optional:            true,
			},
			"subnet_id": schema.StringAttribute{
				MarkdownDescription: "SubnetId.",
				Optional:            true,
			},
			"platform_type": schema.StringAttribute{
				MarkdownDescription: "Platform_type.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"image": schema.StringAttribute{
				MarkdownDescription: "Image.",
				Optional:            true,
			},
			"replicas": schema.Int64Attribute{
				MarkdownDescription: "Replicas.",
				Optional:            true,
			},
		},
	}
}

func (r *NodePoolResource) Create(
	ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage NodePool resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var plan NodePoolState
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call handler for validation and derivation
	diags := r.Handler.PreExpand(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert Terraform state to native Go struct for pathbind
	native := terraformNodePoolToNative(&plan)

	// Create empty SDK struct and expand plan into it
	obj := &v1alpha1.NodePool{}
	if err := pathbind.Expand(ctx, native, obj); err != nil {
		resp.Diagnostics.AddError("Failed to expand plan to SDK struct", err.Error())
		return
	}

	// Call handler for setting unmappable fields
	diags = r.Handler.PostExpand(ctx, &plan, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create via API
	created, err := r.Client.HyperfleetV1alpha1().NodePools(plan.ClusterName.ValueString()).Create(ctx, obj, hfwrappers.CreateOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to create NodePool", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState NodePoolStateNative
	if err := pathbind.Flatten(ctx, created, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags = r.Handler.PostResponse(ctx, created)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeNodePoolToTerraform(&nativeState)

	// Merge API response values into plan to preserve consumer-only fields
	// This keeps user-provided values while adding computed fields from the API
	mergeResponseNodePool(&plan, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &plan, created)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *NodePoolResource) Read(
	ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage NodePool resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var state NodePoolState
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get current resource from API
	obj, err := r.Client.HyperfleetV1alpha1().NodePools(state.ClusterName.ValueString()).Get(ctx, state.Id.ValueString(), hfwrappers.GetOptions{})
	if err != nil {
		if isNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Failed to read NodePool", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState NodePoolStateNative
	if err := pathbind.Flatten(ctx, obj, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags := r.Handler.PostResponse(ctx, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeNodePoolToTerraform(&nativeState)

	// Merge API response values into state to preserve consumer-only fields
	// (fields with no SDK path, e.g. immutable creation-only inputs) that
	// would otherwise be lost since they cannot be reconstructed from the API response.
	mergeResponseNodePool(&state, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &state, obj)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *NodePoolResource) Update(
	ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage NodePool resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var plan NodePoolState
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call handler for validation and derivation
	diags := r.Handler.PreExpand(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert Terraform state to native Go struct for pathbind
	native := terraformNodePoolToNative(&plan)

	// Create empty SDK struct and expand plan into it
	obj := &v1alpha1.NodePool{}
	if err := pathbind.Expand(ctx, native, obj); err != nil {
		resp.Diagnostics.AddError("Failed to expand plan to SDK struct", err.Error())
		return
	}

	// Call handler for setting unmappable fields
	diags = r.Handler.PostExpand(ctx, &plan, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Update via API
	updated, err := r.Client.HyperfleetV1alpha1().NodePools(plan.ClusterName.ValueString()).Update(ctx, obj, hfwrappers.UpdateOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to update NodePool", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState NodePoolStateNative
	if err := pathbind.Flatten(ctx, updated, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags = r.Handler.PostResponse(ctx, updated)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeNodePoolToTerraform(&nativeState)

	// Merge API response values into plan to preserve consumer-only fields
	// This keeps user-provided values while adding computed fields from the API
	mergeResponseNodePool(&plan, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &plan, updated)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *NodePoolResource) Delete(
	ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage NodePool resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var state NodePoolState
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.Client.HyperfleetV1alpha1().NodePools(state.ClusterName.ValueString()).Delete(ctx, state.Id.ValueString(), hfwrappers.DeleteOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to delete NodePool", err.Error())
		return
	}

	// Call handler for post-delete side effects
	var emptyResp *v1alpha1.NodePool
	diags := r.Handler.PostResponse(ctx, emptyResp)
	resp.Diagnostics.Append(diags...)
}

func (r *NodePoolResource) ImportState(
	ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage NodePool resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	// Use the ID passed in as the NodePool identifier
	// TODO: For namespaced resources, determine the namespace from context or import ID format
	obj, err := r.Client.HyperfleetV1alpha1().NodePools("").Get(ctx, req.ID, hfwrappers.GetOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to import NodePool", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState NodePoolStateNative
	if err := pathbind.Flatten(ctx, obj, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags := r.Handler.PostResponse(ctx, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	state := nativeNodePoolToTerraform(&nativeState)
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Helper functions for state conversion

// terraformNodePoolToNative converts Terraform framework types to native Go types.
// This is used before pathbind.Expand to prepare input for API calls.
func terraformNodePoolToNative(tf *NodePoolState) *NodePoolStateNative {
	if tf == nil {
		return nil
	}
	native := &NodePoolStateNative{}
	if !tf.Name.IsNull() && !tf.Name.IsUnknown() {
		native.Name = tf.Name.ValueString()
	}
	if !tf.Id.IsNull() && !tf.Id.IsUnknown() {
		native.Id = tf.Id.ValueString()
	}
	if !tf.AutoRepair.IsNull() && !tf.AutoRepair.IsUnknown() {
		b := tf.AutoRepair.ValueBool()
		native.AutoRepair = &b
	}
	if !tf.DisplayName.IsNull() && !tf.DisplayName.IsUnknown() {
		native.DisplayName = tf.DisplayName.ValueString()
	}
	if !tf.Labels.IsNull() && !tf.Labels.IsUnknown() {
		native.Labels = terraformMapToStringMap(tf.Labels)
	}
	if !tf.ClusterName.IsNull() && !tf.ClusterName.IsUnknown() {
		native.ClusterName = tf.ClusterName.ValueString()
	}
	if !tf.Ami.IsNull() && !tf.Ami.IsUnknown() {
		native.Ami = tf.Ami.ValueString()
	}
	if !tf.ImageType.IsNull() && !tf.ImageType.IsUnknown() {
		native.ImageType = tf.ImageType.ValueString()
	}
	if !tf.InstanceProfile.IsNull() && !tf.InstanceProfile.IsUnknown() {
		native.InstanceProfile = tf.InstanceProfile.ValueString()
	}
	if !tf.InstanceType.IsNull() && !tf.InstanceType.IsUnknown() {
		native.InstanceType = tf.InstanceType.ValueString()
	}
	if !tf.CapacityReservationId.IsNull() && !tf.CapacityReservationId.IsUnknown() {
		native.CapacityReservationId = tf.CapacityReservationId.ValueString()
	}
	if !tf.CapacityReservationMarketType.IsNull() && !tf.CapacityReservationMarketType.IsUnknown() {
		native.CapacityReservationMarketType = tf.CapacityReservationMarketType.ValueString()
	}
	if !tf.Preference.IsNull() && !tf.Preference.IsUnknown() {
		native.Preference = tf.Preference.ValueString()
	}
	if !tf.PlacementMarketType.IsNull() && !tf.PlacementMarketType.IsUnknown() {
		native.PlacementMarketType = tf.PlacementMarketType.ValueString()
	}
	if !tf.MaxPrice.IsNull() && !tf.MaxPrice.IsUnknown() {
		native.MaxPrice = tf.MaxPrice.ValueString()
	}
	if !tf.Tenancy.IsNull() && !tf.Tenancy.IsUnknown() {
		native.Tenancy = tf.Tenancy.ValueString()
	}
	if !tf.ResourceTags.IsNull() && !tf.ResourceTags.IsUnknown() {
		native.ResourceTags = tf.ResourceTags.ValueString()
	}
	if !tf.Encrypted.IsNull() && !tf.Encrypted.IsUnknown() {
		b := tf.Encrypted.ValueBool()
		native.Encrypted = &b
	}
	if !tf.EncryptionKey.IsNull() && !tf.EncryptionKey.IsUnknown() {
		native.EncryptionKey = tf.EncryptionKey.ValueString()
	}
	if !tf.Iops.IsNull() && !tf.Iops.IsUnknown() {
		i := tf.Iops.ValueInt64()
		native.Iops = &i
	}
	if !tf.Size.IsNull() && !tf.Size.IsUnknown() {
		i := tf.Size.ValueInt64()
		native.Size = &i
	}
	if !tf.RootVolumeType.IsNull() && !tf.RootVolumeType.IsUnknown() {
		native.RootVolumeType = tf.RootVolumeType.ValueString()
	}
	if !tf.SecurityGroups.IsNull() && !tf.SecurityGroups.IsUnknown() {
		native.SecurityGroups = tf.SecurityGroups.ValueString()
	}
	if !tf.Filters.IsNull() && !tf.Filters.IsUnknown() {
		native.Filters = tf.Filters.ValueString()
	}
	if !tf.SubnetId.IsNull() && !tf.SubnetId.IsUnknown() {
		native.SubnetId = tf.SubnetId.ValueString()
	}
	if !tf.Platform_type.IsNull() && !tf.Platform_type.IsUnknown() {
		native.Platform_type = tf.Platform_type.ValueString()
	}
	if !tf.Image.IsNull() && !tf.Image.IsUnknown() {
		native.Image = tf.Image.ValueString()
	}
	if !tf.Replicas.IsNull() && !tf.Replicas.IsUnknown() {
		i := int32(tf.Replicas.ValueInt64())
		native.Replicas = &i
	}
	return native
}

// nativeNodePoolToTerraform converts native Go types to Terraform framework types.
// This is used after pathbind.Flatten to prepare output for state persistence.
func nativeNodePoolToTerraform(native *NodePoolStateNative) *NodePoolState {
	if native == nil {
		return nil
	}
	tf := &NodePoolState{}
	tf.Name = toTerraformString(native.Name)
	tf.Id = toTerraformString(native.Id)
	tf.AutoRepair = toTerraformBoolPtr(native.AutoRepair)
	tf.DisplayName = toTerraformString(native.DisplayName)
	tf.Labels = toTerraformMap(native.Labels)
	tf.ClusterName = toTerraformString(native.ClusterName)
	tf.Ami = toTerraformString(native.Ami)
	tf.ImageType = toTerraformString(native.ImageType)
	tf.InstanceProfile = toTerraformString(native.InstanceProfile)
	tf.InstanceType = toTerraformString(native.InstanceType)
	tf.CapacityReservationId = toTerraformString(native.CapacityReservationId)
	tf.CapacityReservationMarketType = toTerraformString(native.CapacityReservationMarketType)
	tf.Preference = toTerraformString(native.Preference)
	tf.PlacementMarketType = toTerraformString(native.PlacementMarketType)
	tf.MaxPrice = toTerraformString(native.MaxPrice)
	tf.Tenancy = toTerraformString(native.Tenancy)
	tf.ResourceTags = toTerraformString(native.ResourceTags)
	tf.Encrypted = toTerraformBoolPtr(native.Encrypted)
	tf.EncryptionKey = toTerraformString(native.EncryptionKey)
	tf.Iops = toTerraformInt64Ptr(normalizeOptionalInt64(native.Iops))
	tf.Size = toTerraformInt64Ptr(normalizeOptionalInt64(native.Size))
	tf.RootVolumeType = toTerraformString(native.RootVolumeType)
	tf.SecurityGroups = toTerraformString(native.SecurityGroups)
	tf.Filters = toTerraformString(native.Filters)
	tf.SubnetId = toTerraformString(native.SubnetId)
	tf.Platform_type = toTerraformString(native.Platform_type)
	tf.Image = toTerraformString(native.Image)
	tf.Replicas = toTerraformInt64Ptr(normalizeOptionalInt32ToInt64(native.Replicas))
	return tf
}
