// Code generated by pathbind-gen --mode=tf. DO NOT EDIT.
// Source: pathbind-overrides.yaml

package hyperfleet

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// OidcConfigState holds Terraform state and plan data for OidcConfig resources.
// This struct is used for Terraform schema binding (input plan and output state).
// Fields are tagged with tfsdk (Terraform state key) only.
// DO NOT use hfsdk tags here; use OidcConfigStateNative for pathbind operations.
type OidcConfigState struct {
	Name             types.String `tfsdk:"name"`
	Id               types.String `tfsdk:"id"`
	InstallerRoleArn types.String `tfsdk:"installer_role_arn"`
	Issuer_url       types.String `tfsdk:"issuer_url"`
	SecretArn        types.String `tfsdk:"secret_arn"`
	Type             types.String `tfsdk:"type"`
	Phase            types.String `tfsdk:"phase"`
	Thumbprint       types.String `tfsdk:"thumbprint"`
}

// mergeResponseOidcConfig merges API response values into the plan state.
// Only computed or required fields are merged from the response. Optional fields
// are skipped to preserve user-provided values and avoid overwriting with API defaults.
func mergeResponseOidcConfig(plan, response *OidcConfigState) {
	if response == nil {
		return
	}
	// Only copy computed and required fields from response, skip optional fields
	// to avoid overwriting user inputs with API-generated default values
	if !response.Id.IsNull() {
		plan.Id = response.Id
	}
	if !response.Issuer_url.IsNull() {
		plan.Issuer_url = response.Issuer_url
	}
	if !response.Phase.IsNull() {
		plan.Phase = response.Phase
	}
	if !response.Thumbprint.IsNull() {
		plan.Thumbprint = response.Thumbprint
	}
}
