// Code generated by pathbind-gen --mode=tf. DO NOT EDIT.
// Source: pathbind-overrides.yaml

package hyperfleet

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	hyperfleet "github.com/openshift-online/rosa-hyperfleet-api/clientset"
	pathbind "github.com/openshift-online/rosa-hyperfleet-api/clientset/pathbind"
	hfwrappers "github.com/openshift-online/rosa-hyperfleet-api/clientset/platform"

	"github.com/terraform-redhat/terraform-provider-rhcs/provider/providerdata"
)

var _ resource.Resource = &OidcConfigResource{}
var _ resource.ResourceWithConfigure = &OidcConfigResource{}
var _ resource.ResourceWithImportState = &OidcConfigResource{}

// NewOidcConfig creates a new OidcConfig resource.
func NewOidcConfig() resource.Resource {
	return &OidcConfigResource{}
}

// OidcConfigHandler defines consumer-specific logic for OidcConfig operations.
type OidcConfigHandler interface {
	// PreExpand is called before pathbind.Expand to validate inputs and derive computed fields.
	// Example: validate name length, compute RolesRef from prefix, derive region from AZs.
	PreExpand(ctx context.Context, input *OidcConfigState) diag.Diagnostics

	// PostExpand is called after pathbind.Expand and before the API call.
	// Use this to set SDK fields that pathbind cannot express (enum constants, computed structs).
	PostExpand(ctx context.Context, input *OidcConfigState, obj *v1alpha1.OidcConfig) diag.Diagnostics

	// PostResponse is called after API calls (Create, Read, Update, Delete).
	// Use this for output formatting, side effects, and post-processing.
	PostResponse(ctx context.Context, resp *v1alpha1.OidcConfig) diag.Diagnostics

	// PostFlatten is called after pathbind.Flatten converts API response to state.
	// Use this to populate computed fields, adjust state values, or perform post-processing
	// that requires access to both the API response and the state being built.
	PostFlatten(ctx context.Context, state *OidcConfigState, resp *v1alpha1.OidcConfig)
}

// OidcConfigResource manages OidcConfig resources via the hyperfleet Platform API.
type OidcConfigResource struct {
	// Client is the hyperfleet SDK client configured by the provider.
	Client hyperfleet.Interface

	// AccountID is the AWS account ID configured by the provider.
	AccountID string

	// CallerARN is the SigV4 caller ARN configured by the provider.
	CallerARN string

	// Handler is the consumer-provided implementation of OidcConfigHandler.
	Handler OidcConfigHandler
}

func (r *OidcConfigResource) Metadata(
	_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_oidcconfig_hyperfleet"
}

func (r *OidcConfigResource) Configure(
	_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse,
) {
	if req.ProviderData == nil {
		return
	}

	shared, ok := req.ProviderData.(*providerdata.ProviderSharedData)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *providerdata.ProviderSharedData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.Client = shared.HyperfleetClient
	r.AccountID = shared.HyperfleetAccountID
	r.CallerARN = shared.HyperfleetCallerARN

	// Initialize the handler via factory function
	r.Handler = NewOidcConfigHandlerImpl(shared.HyperfleetClient, shared.HyperfleetAccountID, shared.HyperfleetCallerARN)
}

func (r *OidcConfigResource) Schema(
	_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse,
) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages OidcConfig resources.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Id.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"installer_role_arn": schema.StringAttribute{
				MarkdownDescription: "InstallerRoleArn.",
				Optional:            true,
			},
			"issuer_url": schema.StringAttribute{
				MarkdownDescription: "IssuerUrl.",
				Optional:            true,
			},
			"secret_arn": schema.StringAttribute{
				MarkdownDescription: "SecretArn.",
				Optional:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Type.",
				Optional:            true,
			},
		},
	}
}

func (r *OidcConfigResource) Create(
	ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage OidcConfig resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var plan OidcConfigState
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call handler for validation and derivation
	diags := r.Handler.PreExpand(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert Terraform state to native Go struct for pathbind
	native := terraformOidcConfigToNative(&plan)

	// Create empty SDK struct and expand plan into it
	obj := &v1alpha1.OidcConfig{}
	if err := pathbind.Expand(ctx, native, obj); err != nil {
		resp.Diagnostics.AddError("Failed to expand plan to SDK struct", err.Error())
		return
	}

	// Call handler for setting unmappable fields
	diags = r.Handler.PostExpand(ctx, &plan, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create via API
	created, err := r.Client.HyperfleetV1alpha1().OidcConfigs().Create(ctx, obj, hfwrappers.CreateOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to create OidcConfig", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState OidcConfigStateNative
	if err := pathbind.Flatten(ctx, created, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags = r.Handler.PostResponse(ctx, created)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeOidcConfigToTerraform(&nativeState)

	// Merge API response values into plan to preserve consumer-only fields
	// This keeps user-provided values while adding computed fields from the API
	mergeResponseOidcConfig(&plan, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &plan, created)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OidcConfigResource) Read(
	ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage OidcConfig resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var state OidcConfigState
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get current resource from API
	obj, err := r.Client.HyperfleetV1alpha1().OidcConfigs().Get(ctx, state.Id.ValueString(), hfwrappers.GetOptions{})
	if err != nil {
		if isNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Failed to read OidcConfig", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState OidcConfigStateNative
	if err := pathbind.Flatten(ctx, obj, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags := r.Handler.PostResponse(ctx, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeOidcConfigToTerraform(&nativeState)

	// Merge API response values into state to preserve consumer-only fields
	// (fields with no SDK path, e.g. immutable creation-only inputs) that
	// would otherwise be lost since they cannot be reconstructed from the API response.
	mergeResponseOidcConfig(&state, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &state, obj)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *OidcConfigResource) Update(
	ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage OidcConfig resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var plan OidcConfigState
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Call handler for validation and derivation
	diags := r.Handler.PreExpand(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert Terraform state to native Go struct for pathbind
	native := terraformOidcConfigToNative(&plan)

	// Create empty SDK struct and expand plan into it
	obj := &v1alpha1.OidcConfig{}
	if err := pathbind.Expand(ctx, native, obj); err != nil {
		resp.Diagnostics.AddError("Failed to expand plan to SDK struct", err.Error())
		return
	}

	// Call handler for setting unmappable fields
	diags = r.Handler.PostExpand(ctx, &plan, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Update via API
	updated, err := r.Client.HyperfleetV1alpha1().OidcConfigs().Update(ctx, obj, hfwrappers.UpdateOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to update OidcConfig", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState OidcConfigStateNative
	if err := pathbind.Flatten(ctx, updated, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags = r.Handler.PostResponse(ctx, updated)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	responseState := nativeOidcConfigToTerraform(&nativeState)

	// Merge API response values into plan to preserve consumer-only fields
	// This keeps user-provided values while adding computed fields from the API
	mergeResponseOidcConfig(&plan, responseState)

	// Call handler to populate computed fields and adjust state after flatten
	r.Handler.PostFlatten(ctx, &plan, updated)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OidcConfigResource) Delete(
	ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage OidcConfig resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	var state OidcConfigState
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.Client.HyperfleetV1alpha1().OidcConfigs().Delete(ctx, state.Id.ValueString(), hfwrappers.DeleteOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to delete OidcConfig", err.Error())
		return
	}

	// Call handler for post-delete side effects
	var emptyResp *v1alpha1.OidcConfig
	diags := r.Handler.PostResponse(ctx, emptyResp)
	resp.Diagnostics.Append(diags...)
}

func (r *OidcConfigResource) ImportState(
	ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse,
) {
	// Validate that hyperfleet is configured
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Hyperfleet not configured",
			//nolint:lll
			"The hyperfleet_url provider attribute is required to manage OidcConfig resources. Set it explicitly in the provider configuration or via the RHCS_HYPERFLEET_URL environment variable.",
		)
		return
	}

	// Use the ID passed in as the OidcConfig identifier
	obj, err := r.Client.HyperfleetV1alpha1().OidcConfigs().Get(ctx, req.ID, hfwrappers.GetOptions{})
	if err != nil {
		resp.Diagnostics.AddError("Failed to import OidcConfig", err.Error())
		return
	}

	// Flatten response into native state
	var nativeState OidcConfigStateNative
	if err := pathbind.Flatten(ctx, obj, &nativeState); err != nil {
		resp.Diagnostics.AddError("Failed to flatten API response to state", err.Error())
		return
	}

	// Call handler for post-processing
	diags := r.Handler.PostResponse(ctx, obj)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Convert native state to Terraform state
	state := nativeOidcConfigToTerraform(&nativeState)
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Helper functions for state conversion

// terraformOidcConfigToNative converts Terraform framework types to native Go types.
// This is used before pathbind.Expand to prepare input for API calls.
func terraformOidcConfigToNative(tf *OidcConfigState) *OidcConfigStateNative {
	if tf == nil {
		return nil
	}
	native := &OidcConfigStateNative{}
	if !tf.Name.IsNull() && !tf.Name.IsUnknown() {
		native.Name = tf.Name.ValueString()
	}
	if !tf.Id.IsNull() && !tf.Id.IsUnknown() {
		native.Id = tf.Id.ValueString()
	}
	if !tf.InstallerRoleArn.IsNull() && !tf.InstallerRoleArn.IsUnknown() {
		native.InstallerRoleArn = tf.InstallerRoleArn.ValueString()
	}
	if !tf.IssuerUrl.IsNull() && !tf.IssuerUrl.IsUnknown() {
		native.IssuerUrl = tf.IssuerUrl.ValueString()
	}
	if !tf.SecretArn.IsNull() && !tf.SecretArn.IsUnknown() {
		native.SecretArn = tf.SecretArn.ValueString()
	}
	if !tf.Type.IsNull() && !tf.Type.IsUnknown() {
		native.Type = tf.Type.ValueString()
	}
	return native
}

// nativeOidcConfigToTerraform converts native Go types to Terraform framework types.
// This is used after pathbind.Flatten to prepare output for state persistence.
func nativeOidcConfigToTerraform(native *OidcConfigStateNative) *OidcConfigState {
	if native == nil {
		return nil
	}
	tf := &OidcConfigState{}
	tf.Name = toTerraformString(native.Name)
	tf.Id = toTerraformString(native.Id)
	tf.InstallerRoleArn = toTerraformString(native.InstallerRoleArn)
	tf.IssuerUrl = toTerraformString(native.IssuerUrl)
	tf.SecretArn = toTerraformString(native.SecretArn)
	tf.Type = toTerraformString(native.Type)
	return tf
}
