// Code generated by pathbind-gen --mode=tf. DO NOT EDIT.
// Source: pathbind-overrides.yaml

package hyperfleet

// OidcConfigStateNative holds native Go types for OidcConfig state.
// This is an intermediate struct used internally with pathbind.Expand/Flatten
// to convert between SDK types and Terraform framework types.
// Fields are tagged with hfsdk (SDK path for pathbind operations).
type OidcConfigStateNative struct {
	Name             string `hfsdk:"metadata.name"`
	Id               string `hfsdk:"metadata.uid"`
	InstallerRoleArn string `hfsdk:"spec.installerRoleArn"`
	IssuerUrl        string `hfsdk:"spec.issuerUrl"`
	SecretArn        string `hfsdk:"spec.secretArn"`
	Type             string `hfsdk:"spec.type"`
}
