token = "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2ODUzNjIwODEsImp0aSI6IjA3NjVkMmE4LTIwYjktNGEwOC04ZmQ3LWI4NzI3MTIwMTIxMiIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpoYWMtZWNvc3lzdGVtIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImNsb3VkLXNlcnZpY2VzIiwibm9uY2UiOiJhOWFlNzczNC1iNDA0LTQwMTAtYjY2Mi0xNWY4NjZhOTU2M2UiLCJzZXNzaW9uX3N0YXRlIjoiOTM2MWJkYjQtZGZiYS00NTk2LWJlM2YtMWU5YTYwMjc2NDA1Iiwic2NvcGUiOiJvcGVuaWQgYXBpLmlhbS5zZXJ2aWNlX2FjY291bnRzIGFwaS5pYW0ub3JnYW5pemF0aW9uIG9mZmxpbmVfYWNjZXNzIiwic2lkIjoiOTM2MWJkYjQtZGZiYS00NTk2LWJlM2YtMWU5YTYwMjc2NDA1In0.NECrUAFktGhmPBo7zyWGtot8GebpTRbqDnSuujhSB3I"
operator_role_prefix = "terraform-operator-3105"
url = "https://api.stage.openshift.com"
account_role_prefix = "amalykhi"
cloud_region = "us-east-1"
#availability_zones = ["us-east-2a", "us-east-2b", "us-east-2c"]
availability_zones = ["us-east-1b"]
count = 3
