output "oidc_config_id" {
  value       = time_sleep.wait_10_seconds.triggers["oidc_config_id"]
  description = "The unique identifier associated with users authenticated through OpenID Connect (OIDC) generated by this OIDC config."
}

output "operator_role_prefix" {
  value       = time_sleep.role_resources_propagation.triggers["operator_role_prefix"]
  description = "Prefix used for generated AWS operator policies."
}

output "account_role_prefix" {
  value = var.account_role_prefix
}