---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rhcs_cluster Resource - terraform-provider-rhcs"
subcategory: ""
description: |-
  OpenShift managed cluster.
---

# rhcs_cluster (Resource)

OpenShift managed cluster.



<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cloud_provider` (String) Cloud provider identifier, for example 'aws'.
- `cloud_region` (String) Cloud region identifier, for example 'us-east-1'.
- `name` (String) Name of the cluster.
- `product` (String) Product ID OSD or Rosa

### Optional

- `availability_zones` (List of String) Availability zones.
- `aws_access_key_id` (String, Sensitive) Identifier of the AWS access key.
- `aws_account_id` (String) Identifier of the AWS account.
- `aws_additional_compute_security_group_ids` (List of String) AWS additional compute security group ids.
- `aws_additional_control_plane_security_group_ids` (List of String) AWS additional control plane security group ids.
- `aws_additional_infra_security_group_ids` (List of String) AWS additional infra security group ids.
- `aws_private_link` (Boolean) Provides private connectivity between VPCs, AWS services, and your on-premises networks, without exposing your traffic to the public internet.
- `aws_secret_access_key` (String, Sensitive) AWS access key.
- `aws_subnet_ids` (List of String) AWS subnet IDs.
- `ccs_enabled` (Boolean) Enables customer cloud subscription.
- `compute_machine_type` (String) Identifier of the machine type used by the compute nodes, for example `r5.xlarge`. Use the `ocm_machine_types` data source to find the possible values.
- `compute_nodes` (Number) Number of compute nodes of the cluster.
- `domain_prefix` (String) The domain prefix is optionally assigned by the user.It will appear in the Cluster's domain when the cluster is provisioned. If not supplied, it will be auto generated
- `host_prefix` (Number) Length of the prefix of the subnet assigned to each node.
- `machine_cidr` (String) Block of IP addresses for nodes.
- `multi_az` (Boolean) Indicates if the cluster should be deployed to multiple availability zones. Default value is 'false'.
- `pod_cidr` (String) Block of IP addresses for pods.
- `properties` (Map of String) User defined properties.
- `proxy` (Attributes) proxy (see [below for nested schema](#nestedatt--proxy))
- `service_cidr` (String) Block of IP addresses for services.
- `version` (String) Identifier of the version of OpenShift, for example 'openshift-v4.1.0'.
- `wait` (Boolean) Wait till the cluster is ready.

### Read-Only

- `api_url` (String) URL of the API server.
- `console_url` (String) URL of the console.
- `id` (String) Unique identifier of the cluster.
- `state` (String) State of the cluster.

<a id="nestedatt--proxy"></a>
### Nested Schema for `proxy`

Optional:

- `additional_trust_bundle` (String) A string containing a PEM-encoded X.509 certificate bundle that will be added to the nodes' trusted certificate store. To reset please provide '' (empty string)
- `http_proxy` (String) HTTP proxy. To reset please provide '' (empty string)
- `https_proxy` (String) HTTPS proxy. To reset please provide '' (empty string)
- `no_proxy` (String) No proxy. To reset please provide '' (empty string)
