---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rhcs_log_forwarder Resource - terraform-provider-rhcs"
subcategory: ""
description: |-
  Manages log forwarder configuration for a cluster
---

# rhcs_log_forwarder (Resource)

Manages log forwarder configuration for a cluster



<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster` (String) Identifier of the cluster. After the creation of the resource, it is not possible to update the attribute value.

### Optional

- `applications` (List of String) List of additional applications to forward logs for.
- `cloudwatch` (Attributes) CloudWatch configuration for log forwarding destination. (see [below for nested schema](#nestedatt--cloudwatch))
- `groups` (Attributes List) List of log forwarder groups. (see [below for nested schema](#nestedatt--groups))
- `s3` (Attributes) S3 configuration for log forwarding destination. (see [below for nested schema](#nestedatt--s3))

### Read-Only

- `id` (String) Unique identifier of the log forwarder.

<a id="nestedatt--cloudwatch"></a>
### Nested Schema for `cloudwatch`

Required:

- `log_distribution_role_arn` (String) The ARN of the IAM role for log distribution.
- `log_group_name` (String) The name of the CloudWatch log group.


<a id="nestedatt--groups"></a>
### Nested Schema for `groups`

Required:

- `id` (String) The identifier of the log forwarder group.
- `version` (String) The version of the log forwarder group.


<a id="nestedatt--s3"></a>
### Nested Schema for `s3`

Required:

- `bucket_name` (String) The name of the S3 bucket.

Optional:

- `bucket_prefix` (String) The prefix to use for objects stored in the S3 bucket.
