---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rhcs_tuning_config Resource - terraform-provider-rhcs"
subcategory: ""
description: |-
  Edit a cluster tuning config
---

# rhcs_tuning_config (Resource)

Edit a cluster tuning config

## Example Usage

```terraform
resource "rhcs_tuning_config" "hcp_tuning_config" {
  cluster = "cluster-id-123"
  name    = "my-config"
  spec = jsonencode({
    "profile" : [
      {
        "data" : "[main]\nsummary=Custom OpenShift profile\ninclude=openshift-node\n\n[sysctl]\nvm.dirty_ratio=\"65\"\n",
        "name" : "tuned-72521-1-profile"
      }
    ],
    "recommend" : [
      {
        "priority" : 20,
        "profile" : "tuned-72521-1-profile"
      }
    ]
  })
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster` (String) Identifier of the cluster. After the creation of the resource, it is not possible to update the attribute value.
- `name` (String) Name of the tuning configuration. After the creation of the resource, it is not possible to update the attribute value.
- `spec` (String) Definition of the spec. It is required to supply this field wrapped in a jsonencode call. Example: jsonencode({<tuning_config_spec})

### Read-Only

- `id` (String) Unique identifier of the tuning config.
