#!/bin/bash -ex
#
# Copyright (c) 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Checks are performed by the `run_full_cycle_tests.py` script, which is
# written in Python. This script only creates a virtual environment and then
# runs it.

# Prepare the environment:
if [ ! -z "${WORKSPACE}" ]; then
  source jenkins/environment.sh
fi

# Add the `bin` directory of the user to the path:
export PATH="${PATH}:${HOME}/bin:${HOME}/go/bin"

# Without this the Python scripts will potential have problems to decode some
# of the output generated by the programs, as it is UTF-8 regardless of the
# configuration of the environment:
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

#install terraform
yum install -y yum-utils
yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
yum -y install terraform

# Create a Python virtual environment, install the dependencies, and run the
# `run_full_cycle_tests.py` script:
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r build/requirements.txt
exec ./run_full_cycle_tests.py
