---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rhcs_image_mirrors Data Source - terraform-provider-rhcs"
subcategory: ""
description: |-
  Fetches image mirrors for a ROSA HCP cluster
---

# rhcs_image_mirrors (Data Source)

Fetches image mirrors for a ROSA HCP cluster



<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster_id` (String) The ID of the ROSA cluster

### Read-Only

- `image_mirrors` (Attributes List) List of image mirrors for the cluster (see [below for nested schema](#nestedatt--image_mirrors))

<a id="nestedatt--image_mirrors"></a>
### Nested Schema for `image_mirrors`

Read-Only:

- `creation_timestamp` (String) Timestamp when the image mirror was created
- `id` (String) The unique identifier of the image mirror
- `last_update_timestamp` (String) Timestamp when the image mirror was last updated
- `mirrors` (List of String) List of mirror registries
- `source` (String) The source registry that will be mirrored
- `type` (String) The type of mirror
