---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rhcs_trusted_ip_addresses Data Source - terraform-provider-rhcs"
subcategory: ""
description: |-
  List of trusted IP addresses
---

# rhcs_trusted_ip_addresses (Data Source)

List of trusted IP addresses



<!-- schema generated by tfplugindocs -->
## Schema

### Read-Only

- `items` (Attributes List) List of all trusted IP addresses. (see [below for nested schema](#nestedatt--items))
- `total` (Number) Total number of items in the result set.

<a id="nestedatt--items"></a>
### Nested Schema for `items`

Read-Only:

- `enabled` (Boolean) Indicates if the IP is enabled.
- `id` (String) IP address.
